from config.models import report_llm
from langchain.prompts import ChatPromptTemplate

PROMPT = ChatPromptTemplate.from_template("""You are an expert research analyst. Write a complete, professional research report.

Topic: {original_query}
Research summary: {summary}
Quality score achieved: {quality_score}/10
Total retries: {retry_count}

Write a full structured report in this exact format:

# {original_query}

## Executive Summary
(Write 2-3 sentences summarizing the key takeaways)

## Key Findings
- Finding 1 with brief explanation
- Finding 2 with brief explanation
- Finding 3 with brief explanation
- Finding 4 with brief explanation
- Finding 5 with brief explanation

## Detailed Analysis

### Background and Context
(2-3 paragraphs on the topic background)

### Current State and Trends
(2-3 paragraphs on what is happening now)

### Implications and Future Outlook
(2-3 paragraphs on what this means going forward)

## Conclusion
(1 strong concluding paragraph)

## Research Metadata
- Quality Score: {quality_score}/10
- Research Iterations: {retry_count}
- Generated by: AI Research Analyst Agent (Powered by Ollama)

Write substantively. Each section should have real content, not placeholders.""")

def report_writer_node(state):
    chain  = PROMPT | report_llm
    result = chain.invoke({
        "original_query": state["original_query"],
        "summary":        state.get("summary", ""),
        "quality_score":  state.get("quality_score", 0.0),
        "retry_count":    state.get("retry_count", 0),
    })
    return {
        **state,
        "final_report": result.content,
        "log": state.get("log", []) + ["Report writer completed final report"],
    }
